EClerx.MVC.ConsumeWebAPIUsingAjax/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EClerx.MVC.ConsumeWebAPIUsingAjax.Controllers
{
    public class DepartmentsController : Controller
    {
        // GET: Departments
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }
    }
}

EClerx.MVC.ConsumeWebAPIUsingAjax/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EClerx.MVC.ConsumeWebAPIUsingAjax.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

EClerx.MVC.ConsumeWebAPIUsingAjax/Views/Departments/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Add New Department</h2>

<div class="row">
    <div class="col-md-5">
        <form>
            <div class="mb-3">
                <label>Department Code</label>
                <input type="text" id="Code" class="form-control" />
            </div>
            <div class="mb-3">
                <label>Department Name</label>
                <input type="text" id="Name" class="form-control" />
            </div>
            <div class="mb-3">
                <label>Department Head</label>
                <input type="text" id="Head" class="form-control" />
            </div>
            <div class="mb-3">
                <label>Location</label>
                <input type="text" id="Location" class="form-control" />
            </div>
            <div class="mb-3">
                <button type="button" class="btn btn-primary" id="btnAddNew">Submit</button>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {

            $("#btnAddNew").click(function () {
                var department = {
                    cDepartmentCode: $("#Code").val(),
                    vDepartmentName: $("#Name").val(),
                    vDepartmentHead: $("#Head").val(),
                    vLocation: $("#Location").val()
                };
                //console.log(department);

                $.ajax({
                    url: "http://localhost:50269/api/Departments/AddNew",
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json",
                    data: JSON.stringify(department),
                    success: function (data) {
                        alert("Department Created Successfully");
                        clearText();
                        //console.log(window.location.origin);
                        window.location = window.location.origin + "/Departments/Index";
                    },
                    error: function (err) {
                        // console.log(err);
                        alert(err.responseText);
                    }
                });

                function clearText() {
                    $("#Code").val("");
                    $("#Name").val("");
                    $("#Head").val("");
                    $("#Location").val("");
                }
            })
        });
    </script>
}

EClerx.MVC.ConsumeWebAPIUsingAjax/Views/Departments/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Display Departments using JQuery AJAX</h2>
<hr />
@Html.ActionLink("Add New", "Create", "Departments")
<div class="row">
    <div class="col-md-8">
        <table id="tblDepartment" class="table table-striped table-hover">
            <tr>
                <th>Department Code</th>
                <th>Department Name</th>
                <th>Department Head</th>
                <th>Location</th>
            </tr>
        </table>
    </div>
</div>

@section Scripts{
    <script>

        $(document).ready(function () {
            //Using JQuery AJAX
            //$.ajax({
            //    url: "http://localhost:50269/api/Departments/GetAll",
            //    type: "GET",
            //    dataType: "json",
            //    contentType: "application/json",
            //    success: function (data) {
            //        var tbl = '';
            //        $.each(data, function (key, item) {
            //            tbl += "<tr>";
            //            tbl += "<td>" + item.cDepartmentCode + "</td>";
            //            tbl += "<td>" + item.vDepartmentName + "</td>";
            //            tbl += "<td>" + item.vDepartmentHead + "</td>";
            //            tbl += "<td>" + item.vLocation + "</td>";
            //            tbl += "</tr>";
            //        });
            //        $(tbl).appendTo($("#tblDepartment"));
            //    },
            //    error: function (err) {
            //        console.log(err);
            //    }
            //});

            //JQuery JSON
            $.getJSON("http://localhost:50269/api/Departments/GetAll", function (data) {
                var tbl = '';
                $.each(data, function (key, item) {
                    tbl += "<tr>";
                    tbl += "<td>" + item.cDepartmentCode + "</td>";
                    tbl += "<td>" + item.vDepartmentName + "</td>";
                    tbl += "<td>" + item.vDepartmentHead + "</td>";
                    tbl += "<td>" + item.vLocation + "</td>";
                    tbl += "</tr>";
                });
                $(tbl).appendTo($("#tblDepartment"));
            });
        });
    </script>

}

EClerx.MVC.ConsumeWebAPIUsingAjax/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

EClerx.MVC.ConsumeWebAPIUsingAjax/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EClerx.MVC.ConsumeWebAPIUsingAjax/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

EClerx.MVC.ConsumeWebAPIUsingAjax/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>